---
- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0700'
  loop: "{{ observability_dir_paths }}"


- name: Set kernel param required by SigNoz
  ansible.posix.sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    reload: true

- name: Copy Logstash config file
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0755'
  loop: "{{ logstash_parsers_config }}"
  notify:
    - Restart signoz container

- name: Copy docker-compose files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0600'
  loop:
    - src: templates/docker-compose/dc-signoz.yml.j2
      dest: "{{ observability_docker_compose_path }}/dc-signoz.yml"

- name: Start SigNoz stack
  community.docker.docker_compose_v2:
    project_src: "{{ observability_docker_compose_path }}"
    files:
      - dc-signoz.yml
    remove_orphans: true
