---
role_name_check: 1
dependency:
  name: galaxy
  options:
    ignore-certs: true
    ignore-errors: true
    role-file: requirements_dev.yml
    requirements-file: requirements.yml
    force: ${AXOL_FORCE:-true}

driver:
  name: vagrant
  provider:
    name: libvirt
  provision: true
  cachier: machine
  parallel: true
  default_box: '${AXOL_BOX:-generic/ubuntu2004}'

platforms:
  - name: instance
    hostname: axol-test-02
    config_options:
      ssh.keep_alive: true
      ssh.remote_user: 'vagrant'
      synced_folder: false
    memory: 8192
    cpus: 8
    provider_options:
      video_type: 'vga'
      driver: 'kvm'
      cpu_mode: 'host-passthrough'
      video_vram: '16384'


provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"
  playbooks:
    converge: ../resources/playbooks/converge.yml
    prepare: ../resources/playbooks/prepare.yml
  inventory:
    group_vars:
      all:
        clients:
          execution: ${AXOL_EXECUTION:-geth}
          consensus: ${AXOL_CONSENSUS:-lighthouse}
          validator: ${AXOL_VALIDATOR:-lighthouse}
        host_ip_address_to_bind_to: 0.0.0.0


verifier:
  name: ansible


scenario:
  name: obs_only
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
